apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets-es

spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_root_user
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_root_password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: POSTGRES_NON_ROOT_USER
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_user
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: POSTGRES_NON_ROOT_PASSWORD
    remoteRef:
      key: secrets-k8/monitoring/grafana
      property: db_password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None