cassandra:
  persistance:
    enabled: true
    storageClass: "nfs-client"
    size: "500Gi"
  dbUser:
    existingSecret:
      name: cassandra-secret
      forcePassword: true
      keyMapping:
        cassandra-password: password