dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.5.7
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.0
name: grafana
version: 10.5.7
apiVersion: v2
type: application


