type: application
version: 10.5.5
apiVersion: v2
dependencies:
- version: 10.5.5
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.6.0
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common
name: grafana


