type: application
apiVersion: v2
version: 10.5.12
dependencies:
- version: 10.5.12
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.6.2
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common
name: grafana


