apiVersion: v2
version: 4.6.2
name: grafana
type: application
dependencies:
- version: 10.5.8
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.6.2
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common


