version: 10.4.0
type: application
apiVersion: v2
name: grafana
dependencies:
- version: 10.4.0
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.5.0
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common


