version: 4.6.0
name: grafana
apiVersion: v2
dependencies:
- version: 10.5.4
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.6.0
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common
type: application


