dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.5.3
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.5.0
apiVersion: v2
version: 10.5.3
name: grafana
type: application


