version: 10.3.0
type: application
dependencies:
- version: 10.3.0
  name: grafana
  repository: https://grafana.github.io/helm-charts
- version: 4.4.0
  name: common
  repository: https://bjw-s-labs.github.io/helm-charts
name: grafana
apiVersion: v2


