version: 10.5.6
name: grafana
type: application
apiVersion: v2
dependencies:
- version: 10.5.6
  name: grafana
  repository: https://grafana.github.io/helm-charts
- version: 4.6.0
  name: common
  repository: https://bjw-s-labs.github.io/helm-charts


