name: grafana
type: application
dependencies:
- repository: https://grafana.github.io/helm-charts
  name: grafana
  version: 10.5.13
- repository: https://bjw-s-labs.github.io/helm-charts
  name: common
  version: 4.6.2
apiVersion: v2
version: 10.5.13


