version: 10.5.15
type: application
dependencies:
- repository: https://grafana.github.io/helm-charts
  version: 10.5.15
  name: grafana
- repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.2
  name: common
apiVersion: v2
name: grafana


