apiVersion: v2
appVersion: 9.4.7
name: grafana
version: 8.4.1
type: application
dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.4.1
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 11.1.14


