name: grafana
type: application
apiVersion: v2
version: 10.2.0
dependencies:
- version: 10.2.0
  repository: https://grafana.github.io/helm-charts
  name: grafana
- version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts
  name: common


