type: application
apiVersion: v2
version: 10.5.1
dependencies:
- name: grafana
  version: 10.5.1
  repository: https://grafana.github.io/helm-charts
- name: common
  version: 4.5.0
  repository: https://bjw-s-labs.github.io/helm-charts
name: grafana


