apiVersion: v2
type: application
version: 4.6.1
dependencies:
- repository: https://grafana.github.io/helm-charts
  name: grafana
  version: 10.5.8
- repository: https://bjw-s-labs.github.io/helm-charts
  name: common
  version: 4.6.1
name: grafana


