type: application
version: 10.3.2
apiVersion: v2
name: grafana
dependencies:
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.3.2
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.5.0


