version: 8.10.4
name: grafana
type: application
apiVersion: v2
appVersion: 9.4.7
dependencies:
- repository: https://grafana.github.io/helm-charts
  name: grafana
  version: 8.10.4
- repository: https://charts.bitnami.com/bitnami
  name: mysql
  version: 12.3.1


